server:
  port: 8888

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials Access-Control-Allow-Methods Access-Control-Allow-Headers, RETAIN_UNIQUE
      server:
        webflux:
          routes:
          - id: event-ticket-service
            uri: http://localhost:8082
            predicates:
              - Path=/api/events/**, /api/tickets/**
            filters:
              - name: RequestRateLimiter
                args:
                  redis-rate-limiter.replenishRate: 10
                  redis-rate-limiter.burstCapacity: 20
                  key-resolver: '#{@userKeyResolver}'
          - id: order-service
            uri: http://localhost:8083
            predicates:
              - Path=/api/orders/**
            filters:
              - name: RequestRateLimiter
                args:
                  redis-rate-limiter.replenishRate: 3
                  redis-rate-limiter.burstCapacity: 3
                  key-resolver: '#{@userKeyResolver}'
          - id: payment-service
            uri: ${PAYMENT_SERVICE_URL:http://localhost:8084}
            predicates:
              - Path=/api/v1/payments/**


  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: ${SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_JWK_SET_URI:http://localhost:8080/realms/event-ticketing/protocol/openid-connect/certs}
  data:
    redis:
      host: 127.0.0.1
      port: 6379

management:
  tracing:
    enabled: false
  endpoints:
    web:
      base-path: /actuator
      exposure:
        include: health,info,prometheus
  endpoint:
    health:
      show-details: always
